spring:
  application:
    name: zhengcheng-mall-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
  config:
    import:
      - optional:nacos:zhengcheng-mall-api.properties
  dynamic:
    tp:
      enabled: true
      configType: properties
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always