spring:
  application:
    name: zhengcheng-mall-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
  config:
    import:
      - optional:nacos:zhengcheng-mall-api.properties
  dynamic:
    tp:
      enabled: true
      executors: # 动态线程池配置，都有默认值，采用默认值的可以不配置该项，减少配置量
        notifyItems: # 报警项，不配置自动会按默认值配置（变更通知、容量报警、活性报警、拒绝报警、任务超时报警）
          - type: capacity               # 报警项类型，查看源码 NotifyTypeEnum枚举类
            enabled: true
            threshold: 80                # 报警阈值
            platforms: [ ding,wechat ]     # 可选配置，不配置默认拿上层platforms配置的所以平台
            interval: 120                # 报警间隔（单位：s）
          - type: change
            enabled: true
          - type: liveness
            enabled: true
            threshold: 80
          - type: reject
            enabled: true
            threshold: 1
          - type: run_timeout
            enabled: true
            threshold: 1
          - type: queue_timeout
            enabled: true
            threshold: 1
