<!DOCTYPE html>
<html style="background-color: #e2e2e2;">
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="{{ lay.base.keywords }}">
    <meta name="description" content="{{ lay.base.description }}">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>案例</title>
    <link rel="stylesheet" href="../../res/layui/css/layui.css">
    <link rel="stylesheet" href="../../res/css/global.css">
    <style>
        .header {
            border-bottom: 1px solid #404553;
            border-right: 1px solid #404553;
        }
    </style>
</head>
<body class="fly-full">


<div class="fly-main" style="overflow: hidden;">
    <ul class="fly-case-list">
        <li data-id="1">
            <h2><a href="http://developer.baidu.com/vcast/" target="_blank">百度语音</a></h2>
            <p class="fly-case-desc">在线文字转语音|免费生成语音-百度广播开放平台。</p>
        </li>
    </ul>
</div>

</body>
</html>