<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="即时聊天,socket.io,netty-socketio">
    <meta name="description" content="基于socket.io,使用netty-socketio">
    <link rel="stylesheet" href="${base}/static/dist/css/layui.css">
    <link rel="stylesheet" href="${base}/static/dist/css/global.css">
</head>
<body>

<#include "head.ftlh">

<script src="${base}/static/dist/layui.js"></script>
<script src="${base}/static/js/jsencrypt.min.js"></script>

</body>
</html>