spring:
  application:
    name: zhengcheng-mall-xxl-job
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:zhengcheng-mall-xxl-job.properties
server:
  port: 8084